title: Beck Chamberlain Portfolio
iconURL: assets/img/BClogo2.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  github: BeckCham
  linkedin: https://www.linkedin.com/in/beck-chamberlain-3149831b1/
plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 13910
google_analytics: UA-NNNNNNNN-N
